Obtain terms from new endpoint
gt-scheduler/crawler-v2 pull request #4
Opened 2023-03-04 17:41 UTC by nathangong

Resolves #1

2023-03-06 23:48 UTC, its-edmund submitted a review, later dismissed
LGTM 👍

2023-03-07 14:59 UTC, nhatnghiho approved these changes

2023-03-07 15:24 UTC, nhatnghiho requested changes

2023-03-07 15:24 UTC, nhatnghiho commented on src/steps/list.ts
> +const NUM_TERMS = getIntConfig("NUM_TERMS") ?? 2;
Let's change `NUM_TERMS` to some larger number. This query also returns non-academic terms like `Language Inst IEP: Spring 1 23`, which has a code of "202321" and is filtered out later on line 18-20. As a result, running this query right now only gives us 1 term instead of 2.

2023-03-09 04:22 UTC, jazeved0 commented on src/steps/list.ts
> +    `https://registration.banner.gatech.edu/StudentRegistrationSsb/ssb/classSearch/getTerms?searchTerm=&offset=1&max=${NUM_TERMS}`
fwiw: having direct control over the number of terms that appear in the final crawled results is really useful (via the `NUM_TERMS` config option), and this change seems like it will result in fewer than `NUM_TERMS` terms appearing in the output.

What do you think about over-fetching the terms JSON (since it is probably fairly small/fast to fetch) and then taking the top `NUM_TERMS` valid terms from that? Even if it's something simple like `3 * NUM_TERMS + 10`—just enough to make sure there are at least `NUM_TERMS` valid terms in the fetched JSON.

Then, the change in `.github/workflows/crawling.yml` could be reverted back to `NUM_TERMS: 2`.

cc @nhatnghiho

2023-03-09 12:54 UTC, nhatnghiho commented on src/steps/list.ts
> +    `https://registration.banner.gatech.edu/StudentRegistrationSsb/ssb/classSearch/getTerms?searchTerm=&offset=1&max=${NUM_TERMS}`
Exactly what I have in mind. `NUM_TERMS` in `crawling.yml` shouldn't be changed.

2023-03-15 08:22 UTC, nhatnghiho approved these changes

2023-03-15 08:24 UTC, merged