Fetch Data of a Given Term with Banner 9 API
gt-scheduler/crawler-v2 pull request #9
Opened 2023-03-06 00:25 UTC by samarth52

Resolves #2 

- Banner 9 requires an initial session to be created for a given term to fetch the term data
- Banner 9 requires pagination (limit of 500 sections) and returns data in JSON format
- Changed the download function to generate the session and compile the paginated section data into one large JSON
- Added a max of 10 retries with exponential backoff for each request
- Used async pool to perform all section fetching requests concurrently

2023-03-06 22:32 UTC, therealsharath requested changes
Mostly everything LGTM me other than a few nits! Learnt something new with function currying, super readable code!

2023-03-06 22:32 UTC, therealsharath commented on src/utils.ts
> +export function concatParams(params: Record<string, string | number>): string {
NIT: In terms of type safety in TypeScript, it is generally better practice to convert a number to a string before concatenating it with other strings.

This is because TypeScript is a statically-typed language that provides type checking at compile time. If you accept both strings and numbers in a function that concatenates them, you may run into type errors at runtime if a user accidentally passes in a value of the wrong type.

TL;DR you might wanna explicitly convert numbers to strings before concatenating them - feel free to leave a comment if you disagree!

2023-03-06 22:32 UTC, therealsharath commented on src/steps/download.ts
> +          if (pageMaxSize !== 0) {
NIT: Nested ifs - combine the statements

2023-03-06 23:20 UTC, samarth52 commented on src/utils.ts
> +export function concatParams(params: Record<string, string | number>): string {
Fixed this, i now convert it the number parameters into strings in the `buildParams` function

2023-03-06 23:22 UTC, samarth52 commented on src/steps/download.ts
> +          if (pageMaxSize !== 0) {
I was doing that to throw an error if the outer if statement was false, but I have now changed this to throw an error in the retry functionality (so it sends the request again if null data is returned).

2023-03-07 13:48 UTC, therealsharath approved these changes
Updated error handling looks much cleaner! Ty for addressing the requested changes. 🚢 it!

2023-03-07 13:48 UTC, therealsharath commented on src/index.ts
> +    parse(sections, CURRENT_VERSION)
Great catch on the variable name! Def improves readability!

2023-03-07 16:34 UTC, nhatnghiho commented on src/steps/download.ts
> +    .map((_, i) => 500 * i);
Refer to https://github.com/gt-scheduler/crawler-v2/pull/10#discussion_r1127354381. Replace 500 with a constant.

2023-03-07 16:34 UTC, nhatnghiho commented on src/steps/download.ts
> +  function buildParams(pageOffset: number, pageMaxSize: number) {
There are a couple of nested functions in `download`. Can we bring them outside? I know they're using some variables inside `download` but they obscure the workflow and make it harder to follow.

2023-03-07 19:30 UTC, samarth52 commented on src/steps/download.ts
> +  function buildParams(pageOffset: number, pageMaxSize: number) {
Made the changes. Hopefully `download` looks more readable now.

2023-03-07 19:30 UTC, samarth52 commented on src/steps/download.ts
> +    .map((_, i) => 500 * i);
fixed!

2023-03-07 19:32 UTC, nhatnghiho commented on src/steps/download.ts
> +  }
I tested this with `asyncPool` though but it seems like the page size is the limiting factor for execution time. Decreasing the page size in half (while doubling the number of parallel processes) cut the runtime in half.

2023-03-08 22:33 UTC, samarth52 commented on src/steps/download.ts
> +  }
Have made the changes. The download function now uses a max page size of 75 and the thread count is limited by `DETAILS_CONCURRENCY`

2023-03-09 04:11 UTC, jazeved0 requested changes

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +  const buildParams = buildParamsCurry(term, subject, course, pageMaxSize);
(subjective): I think it's more common in JS (and imo less complex/easier to read) to partially apply functions where they are used instead of where they are originally defined (as is done throughout this file). However, I don't feel strongly and I think it's fine to leave as-is.

```js
// example:
function myFunc(a, b, c) { ... }
const partiallyAppliedFunc = (a, b) => myFunc(a, b, 10);
partiallyAppliedFunc(...);

// vs. what exists throughout this file:
function makePartiallyAppliedMyFunc(c) { return (a, b) => { ... }; }
const partiallyAppliedFunc = makePartiallyAppliedMyFunc(10);
partiallyAppliedFunc(...);
```

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +): Promise<string[]> {
Upon first reading, it's confusing why this function returns a promise that resolves to a `string[]` (since you'd think that a single cookie value (a `string`) is all that is needed).

When I ran it locally, I saw that the endpoint results in more than 1 cookie being set, so I think it's worth adding a comment explaining the return value (and maybe renaming to `generateSearchSessionCookies` (emphasis on the plural `Cookies`)).

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +    course
With 5 parameters, it might be worth changing the function to accept an object so that the parameters can be named explicitly (for example, it's unclear what the `0` literal means).

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +  const { totalCount } = await getFirstSection(1);
What does the 1 here mean (as a value for `sectionOffset`), when the `maxPageSize` is 0. Why not 0? A comment would be helpful here.

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +  }
When deploying this, it will probably be useful to know a couple things;
1. How many requests is GT Scheduler making to OSCAR?
2. How long does it take for each request?
3. How long does it take for all requests to be made?

The crawler already has a simple tracing API that you can use to make sure those appear in the logs. It involves wrapping a block of code in the `span` function. I strongly suggest you use this so that tracing information about the requests is in the logs *before* you have to debug problems in production:

```suggestion
  await span(
    // message:
    "fetching all section JSON pages in thread pool",
    // fields:
    { numThreads, pageSize, numRequests, totalCount, term, subject, course },
    // everything that runs in this block will be timed and have a log printed
    // when it starts and finishes:
    async () => {
      if (numRequests >= 1) {
        const getSectionsPage = getSectionsPageCurry(
          session,
          pageSize,
          term,
          subject,
          course
        );
        const getSectionsPageInNewSpan = async (sectionOffset: number) =>
          span(
            "fetching range of section JSON pages",
            { sectionOffset, pageSize, term, subject, course },
            async () => getSectionsPage(sectionOffset)
          );
        sectionsPages = await asyncPool(
          numThreads,
          offsetArr,
          getSectionsPageInNewSpan
        );
      }
    }
  );
```

Then, to get information out of the logs that the crawler produces, you can run `jq` queries on the log files. JQ is [a command-line tool for querying JSON](https://stedolan.github.io/jq/), and is a really powerful tool to have in your arsenal (IMO it's worth learning the basics if you have the time). There are instructions on the Wiki page at [📚 Useful queries on crawler logs](https://github.com/gt-scheduler/crawler/wiki/%F0%9F%93%9A-Useful-queries-on-crawler-logs) that describe the general workflow, both for querying logs from local runs and from GitHub Actions runs. I'll give a brief example of querying local runs here.

### Example

For example, I ran the crawler using `yarn start-logged` using the above changes. This does two things:
1. It makes the crawler log in JSON format instead of the default human-readable format, which is needed for `jq` to work.
2. It creates a file in the project directory and stores the logs in that.

When I ran it, this produced a file named `2023-03-08T18:39:52-08:00.log` in my project directory. The file contains a bunch of lines that each have a single JSON object on them:

```js
{"ts":"2023-03-09T02:39:53.589Z","message":"starting crawler","level":"info","currentVersion":3,"numTerms":2,"detailsConcurrency":128,"logFormat":"json"}
{"ts":"2023-03-09T02:39:53.590Z","message":"crawling Oscar","level":"info","spanEvent":"start"}
{"ts":"2023-03-09T02:39:53.590Z","message":"listing all terms","level":"info","spanEvent":"start"}
// ...
```

To find the answers to the first and third questions from the top of this comment, I ran the following `jq` query:

```jq
# Get list of log entries for when the crawler finished fetching all section JSON pages for a term:
map(select(.message == "fetching all section JSON pages in thread pool" and .spanEvent == "finish"))
```

```bash
# The beginning of this command is copy-pasted from the Wiki page,
# and the jq query went into the single-quotes after `jq -s`.
#
# Note that this command will probably only work on macOS or Linux.
# If you're on Windows (like I am as I type this), I recommend you set up
# Windows Subsystem for Linux (WSL) to run these commands in:
# https://learn.microsoft.com/en-us/windows/wsl/install
# You might also have luck using Git Bash, as long as you also installed JQ and added it to your path.
$ cat $(find . -type f -name "*.log" | sort -n | tail -1) | jq -s 'map(select(.message == "fetching all section JSON pages in thread pool" and .spanEvent == "finish"))'
[
  {
    "ts": "2023-03-09T02:50:48.420Z",
    "message": "fetching all section JSON pages in thread pool",
    "level": "info",
    "spanEvent": "finish",
    "numThreads": 128,
    "pageSize": 75,
    "numRequests": 92,
    "totalCount": 6864,
    "term": "202305",
    "subject": "",
    "course": "",
    "elapsedMs": 7628.30059
  },
  {
    "ts": "2023-03-09T02:50:55.281Z",
    "message": "fetching all section JSON pages in thread pool",
    "level": "info",
    "spanEvent": "finish",
    "numThreads": 128,
    "pageSize": 75,
    "numRequests": 169,
    "totalCount": 12609,
    "term": "202308",
    "subject": "",
    "course": "",
    "elapsedMs": 14377.194731
  }
]
```

This shows the data for the log entries when the crawler finished fetching all the section JSON pages, for each term that it crawled (in this case, `202305` and `202308`). For example, it took 7.6 seconds to make 92 requests to fetch all the section JSON pages for the Spring 2023 catalog (which has 6,864 sections total).

Similarly, to find the answer to the second question, I ran the following `jq` query:

```sh
# Get list of log entries for when the crawler finished fetching a range of section JSON pages:
map(select(.message == "fetching range of section JSON pages" and .spanEvent == "finish"))
  # Group list of log entries into list of lists, one for each term
  | group_by(.term)
  # For each list of log entries for a term, make a new object with the term as the key
  # and the list ms durations as the value:
  | map({(.[0].term): . | map(.elapsedMs)})
  # Flatten the list of objects into a single object:
  | add
```

```bash
# Same as before, except I used `jq -cs` instead of `jq -s`,
# which makes the output compact instead of pretty-printed:
$ cat $(find . -type f -name "*.log" | sort -n | tail -1) | jq -cs 'map(select(.message == "fetching range of section JSON pages" and .spanEvent == "finish")) | group_by(.term) | map({(.[0].term): . | map(.elapsedMs)}) | add'
{"202305":[916.724343,1843.187001,3325.837721,3455.108626,3685.0323,3732.127843,3880.888984,4147.655827,4315.966535,4420.952544,4445.841966,4589.684096,4818.50202,5000.281077,5046.811776,5073.483672,5091.232361,5212.360264,5230.965741,5290.252101,5295.974028,5320.98629,5330.997224,5347.617179,5379.47903,5430.770896,5440.264414,5533.871689,5557.260935,5585.080099,5630.717162,5642.546917,5662.120389,5674.60311,5682.918513,5694.47608,5714.192909,5749.659481,5760.574941,5766.242828,5779.652367,5816.669339,5831.620744,5833.890666,5846.784985,5853.774667,5868.478109,5881.942371,5878.035767,5880.519258,5914.492966,5922.814029,5949.104865,5962.351831,6003.734261,6002.277596,6023.278469,6049.90549,6054.56099,6081.327163,6096.856614,6096.539652,6146.059233,6156.105332,6169.385752,6178.696781,6218.932724,6230.262727,6238.584992,6252.953109,6274.962182,6288.071132,6293.457033,6297.530387,6325.157323,6366.589466,6377.340179,6392.615308,6405.773037,6495.323099,6547.20273,6596.369143,6609.147686,6748.649755,6761.12361,6939.17614,7074.470014,7178.476135,7249.293774,7269.866277,7328.16721,7621.225029],"202308":[2431.002808,3176.140485,4108.927144,5707.754716,6691.487435,7293.409801,7482.910915,8009.943761,8090.386654,8390.392896,8400.962231,8445.772943,8624.020186,8694.82466,8772.33763,8965.184541999999,9051.520722,9135.863575,9203.645393,9241.052482,9271.16329,9320.094283,9362.244266,9396.894616,9417.038271,9426.600337,9428.478679,9475.871435000001,9584.670805,9663.502963,9760.0874,9860.972674,9894.451529,9981.116112,10006.248867,10027.188155,10048.111554,10046.801251,10062.098039,10079.20402,10119.597788,10185.563901,10231.398702,10263.328831,10329.04568,10416.858302,10538.846819,10561.943359,10565.947835,10574.23205,10597.497474,10651.996218,10794.85733,10856.450309,10855.541315,10880.3359,10888.487406,10918.641655,10925.43518,10964.79524,10965.930857,10987.076789,11043.068918,11058.103727,11070.913709,11101.914777,11128.596931,11191.579021,11320.0588,11353.793683,11382.148595999999,11396.017643,11447.63171,11467.832732,11500.95877,11522 [...]

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +  const { totalCount } = await getFirstSection(1);
This is also a case where not currying/partially-applying the `getSectionsPage` function where it is defined would have been preferrable, since now you have two separate function calls needed just to fully call the function (since you don't really want the currying here).

Like I said, though, I think it's fine to leave as-is

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
>    options: FetchOptions = {}
These arguments don't appear to ever be used anywhere when `download` is called. I'm in favor of removing them, since it's unclear what they're supposed to do (do they filter the results?) and whether they still work (have they been tested?). Plus, having less code means less code to maintain 😄.

Likewise, the `FetchOptions` type could also be removed altogether.

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +              },
I think it is a good idea to pass a [`User-Agent`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) header identifying the crawler so that the OSCAR administrators can attribute the traffic to GT Scheduler. Even though this wasn't there before, I still think it's worth adding it now.

```suggestion
              headers: {
                "Content-Type": "application/x-www-form-urlencoded; charset=UT",
                "User-Agent": "gt-scheduler/crawler",
              },
```

2023-03-09 04:11 UTC, jazeved0 commented on src/steps/download.ts
> +          session.get<BannerResponse>(url).then((res) => {
Same thinking here to add a custom `User-Agent`

2023-03-09 04:12 UTC, jazeved0 commented
By the way, I hope none of the feedback I gave is interpreted as too negative. For what it's worth, I'm really impressed by y'all's ability to get this working with the new API (congrats!! 🎉)

2023-03-10 19:25 UTC, samarth52 commented on src/steps/download.ts
>    options: FetchOptions = {}
`term` is used to select a term whose sections need to be downloaded. In the previous step, we decide which terms to download and then call this function concurrently, so it's a necessity.

`numThreads` is used to limit the number of requests being handled concurrently (when downloading sections), and this is determined by `DETAILS_CONCURRENCY` in `index.ts`. I feel is also a necessity in case someone decreases the page size (which could significantly increase the number of requests made to Banner 9).

`options` is one field that is never used so it would also simplify lots of unused fields. I chose to keep it since it was a parameter in the crawler-v1 `download` function despite not being given a value by any `download` call. I thought it was kept in case the requirement arises to download an entire subject's or course's details, but I can remove it if not required. How you feel about this?

2023-03-11 00:11 UTC, samarth52 commented
@jazeved0 Thanks for all the helpful feedback and comments! I have incorporated all the suggestions and also decided to remove function currying (to improve code readability). Let me know if I should remove the `FetchOptions` parameter based on the previous comment.

2023-03-14 01:18 UTC, jazeved0 commented on src/steps/download.ts
>    options: FetchOptions = {}
My bad, I meant to only suggest removing the "options" parameter. I would be in favor of removing that and its corresponding type. I'm not sure why they were in the original parser code. My thinking is that if they are ever needed in the future, they can easily be added back.

2023-03-14 01:26 UTC, jazeved0 approved these changes
I just had 1 minor suggestion. Great work!

2023-03-14 01:26 UTC, jazeved0 commented on src/steps/download.ts
> +  // using pageOffset of 1.
Great comment 👍

2023-03-14 01:26 UTC, jazeved0 commented on src/steps/download.ts
> +    spanFields,
I'd recommend adding totalCount as a field to the parent span. It will be useful when debugging an error (which would cause the setCompletionFields() line to never get reached).

2023-03-14 20:38 UTC, jazeved0 approved these changes

2023-03-15 08:26 UTC, merged